### ISSUE TITLE
Adjust co/colist handling to support multiple refs to the same callout

### ISSUE THREAD

**Issue by sandersk** [oreillymedia/asciidoctor-htmlbook#104]
Right now, HTMLBook backends don't support markup like the following, which contains a repeated callout ref:

````
---
print "Hello World" <1>
print "Hello World Again" <2>
print "Hello World" <1>
---

<1> Standard print statement
<2> Redundant
````

Adding support for the above is pretty easy if we drop support for link bidirectionality for callout markers (which doesn't work anyway if there's not a 1-to-1 correspondence between markers in listings and markers in callouts below) and just have the callout markers in the listing link to the callout entries below the listing.

**Comment by christopappas** [comment]
Hello,

This is actually resolved via #106 !

Closing.
