### ISSUE TITLE
Propagate AsciiDoc comments to HTMLBook

### ISSUE THREAD

**Issue by sandersk** [oreillymedia/asciidoctor-htmlbook#92]
Right now it looks like comments in AsciiDoc:

````
// This is an AsciiDoc comment
````

Are dropped as part of the conversion to HTMLBook. Possible to preserve them as XML comments. In other words, can we convert the above to:

````xml
<!-- This is an AsciiDoc comment -->
````

**Comment by christopappas** [comment]
Closing this issue for now. This would require an extension to be used (which presupposes Asciidoctor 1.5.4). It's always an option to change our comment markup but for now we're going to leave be.
